---
- name: create interface configuration for device {{ifcfg_device}}
  template: src=ifcfg-dev dest=/etc/sysconfig/network-scripts/ifcfg-{{ifcfg_device}}
            owner=root group=root mode=0644
- command: /sbin/ifup {{ifcfg_device}}
  when: ifcfg_state == "up"
- command: /sbin/ifdown {{ifcfg_device}}
  when: ifcfg_state == "down"

