---
# main.yml for hostname/tasks
- name: check system hostname
  command: hostname
  register: hostname
- name: set system hostname (persistent)
  lineinfile: >
    create=yes state=present regexp="&^HOSTNAME="
    line="HOSTNAME={{inventory_hostname}}" 
    dest=/etc/sysconfig/network
  when: "hostname.stdout.find('localhost') != -1"
- name: set system hostname
  command: hostname {{inventory_hostname}}
  when: "hostname.stdout.find('localhost') != -1"

