---
- include: common.yml
- include: rdo-and-upgrade.yml
- include: setup-root-sshkey.yml
- include: setup-controller-nics.yml

- hosts: controller
  vars:
    CONFIG_NOVA_NETWORK_PUBIF: eth0
    CONFIG_NOVA_NETWORK_PRIVIF: lo
    CONFIG_NOVA_COMPUTE_PRIVIF: lo
    CONFIG_PROVISION_ALL_IN_ONE_OVS_BRIDGE: y
    CONFIG_PROVISION_DEMO: y
    CONFIG_SWIFT_INSTALL: y
    CONFIG_SSH_KEY: /root/.ssh/id_rsa.pub
  roles:
    - role: rdo-havana

- include: setup-openstack.yml

