---
- include: rdo-and-upgrade.yml
- include: setup-root-sshkey.yml
- include: setup-compute.yml
- include: setup-controller-nics.yml

- hosts: controller
  vars:
    CONFIG_NEUTRON_OVS_TENANT_NETWORK_TYPE: gre
    CONFIG_NEUTRON_OVS_TUNNEL_RANGES: 1:1000
    CONFIG_NEUTRON_OVS_TUNNEL_IF: eth1
    CONFIG_NOVA_COMPUTE_HOSTS: rdo-compute-0.default.virt
  roles:
    - role: rdo-havana

- include: setup-neutron.yml
- include: setup-openstack.yml

