- hosts: compute
  roles:
    # This sets up eth1 on all the compute hosts.  gre_endpoint_ip should be
    # defined per-host in the inventory file.
    - role: rhifcfg
      device: eth1
      type: Ethernet
      onboot: yes
      bootproto: none
      ipaddr: "{{gre_endpoint_ip}}"
      netmask: 255.255.255.0
      state: up
