- hosts: compute
  tasks:
    - name: "disable filesystem injection"
      command: sed -i '/^libvirt_inject_partition/ s/=.*/=-2/' /etc/nova/nova.conf
    - name: "check for hardware virtualization support"
      command: egrep 'vmx|svm' /proc/cpuinfo
      register: check_virt
      ignore_errors: true
    - name: "enable kvm acceleration"
      command: sed -i '/^libvirt_type/ s/=.*/=kvm/' /etc/nova/nova.conf
      when: check_virt|success
    - command: openstack-service restart nova

- hosts: controller
  roles:
    - role: image
      image_name: cirros
      image_url: https://launchpad.net/cirros/trunk/0.3.0/+download/cirros-0.3.0-x86_64-disk.img
    - role: flavor
      flavor_name: m1.nano
      flavor_ram: 256
      flavor_disk: 1
      flavor_cpu: 1
    - nova_keypair

