- hosts: controller
  tasks:
    - command: test -f /root/.ssh/id_rsa
      register: keycheck
      ignore_errors: true
    - command: ssh-keygen -N '' -t rsa -b 2048 -f /root/.ssh/id_rsa
      when: keycheck.rc != 0
    - command: grep -f /root/.ssh/id_rsa.pub /root/.ssh/authorized_keys
      ignore_errors: true
      register: keyinstalled
    - shell: cat /root/.ssh/id_rsa.pub >> /root/.ssh/authorized_keys
      when: keyinstalled.rc != 0
    - fetch: src=/root/.ssh/id_rsa.pub dest=sshkeys/ flat=yes

