---
- hosts: controller
  roles:
    - role: neutron_network
      network_name: public
      network_external: true
      network_subnets:
        - {name: public, cidr: "{{CONFIG_PROVISION_DEMO_FLOATRANGE}}",
          dns_server: 192.168.1.1, disable_dhcp: true}
    - role: neutron_network
      network_name: net0
      network_subnets:
        - {name: net0-subnet0, cidr: 10.0.0.0/24, dns_servers: 192.168.1.1}
    - role: neutron_router
      router_name: pubrouter
      router_gateway: public
      router_interfaces:
        - net0-subnet0

