- hosts: controller
  tasks:
    - command: test -f /root/.ssh/id_rsa
      register: keycheck
      ignore_errors: true
    - command: ssh-keygen -N '' -t rsa -b 2048 -f /root/.ssh/id_rsa
      when: keycheck|failed
    - fetch: src=/root/.ssh/id_rsa.pub dest=sshkeys/ flat=yes

- hosts: all
  tasks:
    - copy: src=sshkeys/id_rsa.pub dest=/root/.ssh/controller.pub owner=root mode=0600
    - command: grep -f /root/.ssh/controller.pub /root/.ssh/authorized_keys
      ignore_errors: true
      register: keyinstalled
    - shell: cat /root/.ssh/controller.pub >> /root/.ssh/authorized_keys
      when: keyinstalled|failed

