---
- hosts: all
  roles:
    - common
    - role: yumrepo
      repo_name: RHOS-4
      repo_baseurl: http://ayanami.boston.devel.redhat.com/poodles/rhos-devel-ci/4.0/2013-10-28.2/RHOS-4/$basearch/os
      repo_gpgcheck: 0
    - role: upgrade
      reboot: yes

- include: ../setup-root-sshkey.yml

- hosts:
  - compute
  - network
  roles:
    - role: rhifcfg
      ifcfg_device: "{{ CONFIG_NEUTRON_OVS_TUNNEL_IF }}"
      ifcfg_type: Ethernet
      ifcfg_onboot: yes
      ifcfg_bootproto: none,
      ifcfg_ipaddr: "{{ ovs_tunnel_ipaddr }}"
      ifcfg_netmask: "{{ ovs_tunnel_netmask }}"
      ifcfg_state: up

- hosts: controller
  pre_tasks:
    - name: "BUG: avoid bz 1022686 (Keystone puppet modules fail to parse output of keystone command)"
      command: yum -d1 -y install http://repos.fedorapeople.org/repos/openstack/openstack-havana/epel-6/python-backports-1.0-4.el6.x86_64.rpm
      ignore_errors: true
  roles:
    - havana

- hosts: network
  roles:
    - network_controller
 
- include: ../setup-openstack.yml
- include: ../setup-neutron.yml

