---
# main.yml for nova_keypair/tasks
- command: nova keypair-show {{keypair_name}}
  ignore_errors: true
  register: keypair_check
- copy: src={{keypair_pub_key}} dest=/root/{{keypair_name}}.pub
  when: keypair_check|failed
- shell: >
    . /root/keystonerc_admin;
    nova keypair-add --pub-key /root/{{keypair_name}}.pub {{keypair_name}}
  when: keypair_check|failed

