#!/bin/sh

BASE=default/rhel-6.5-x86_64-base.img
NETWORK=bridge=virbr2,model=virtio
NAME=rdo-grizzly

virsh list --name --all | grep $NAME | xargs -n1 virt-delete

virt-from -f -r 1024 -s 8G -w $NETWORK $BASE $NAME-network
virt-from -f -r 2448 -s 8G -w $NETWORK $BASE $NAME-api
virt-from -f -r 2448 -s 8G -w $NETWORK $BASE $NAME-compute

