---
- hosts: all
  pre_tasks:
    - get_url: >
        url=http://rdo.fedorapeople.org/openstack-grizzly/rdo-release-grizzly.rpm
        dest=/root/rdo-release-grizzly.rpm
      register: repopkg
    - command: yum -d1 -y install /root/rdo-release-grizzly.rpm
      when: repopkg.changed
  roles:
    - common
    - role: upgrade
      reboot: yes
  tasks:
    - service: name=NetworkManager state=stopped enabled=false
      ignore_errors: true
    - yum: name=NetworkManager state=absent
    - service: name=network state=running enabled=true

- include: ../setup-root-sshkey.yml

- hosts:
  - compute
  - network
  roles:
    - role: rhifcfg
      ifcfg_device: "{{ CONFIG_QUANTUM_OVS_TUNNEL_IF }}"
      ifcfg_type: Ethernet
      ifcfg_onboot: yes
      ifcfg_bootproto: none,
      ifcfg_ipaddr: "{{ ovs_tunnel_ipaddr }}"
      ifcfg_netmask: "{{ ovs_tunnel_netmask }}"
      ifcfg_state: up

- hosts: network
  tasks:
    - name: "BZ 1021227: neutron requires python-keystoneclient"
      yum: name=python-keystoneclient state=latest

- hosts: controller
  roles:
    - grizzly

- hosts:
    - compute
    - network
  tasks:
    - name: "BZ 1028591: packstack generates invalid configuration when using GRE tunnels"
      command: >
        sed -i.tunnel 
        -e '/^enable_tunneling/ s/False/True/'
        -e '/enable_tunneling/ a\local_ip={{ovs_tunnel_ipaddr}}'
        -e '/enable_tunneling/ a\tunnel_bridge=br-tun'
        /etc/quantum/plugins/openvswitch/ovs_quantum_plugin.ini
    - command: openstack-service restart quantum

- hosts: compute
  tasks:
    - name: "disable filesystem injection"
      command: sed -i '/^libvirt_inject_partition/ s/=.*/=-2/' /etc/nova/nova.conf
    - command: openstack-service restart nova

- hosts: network
  roles:
    - network_controller
 
- include: ../setup-openstack.yml
- include: ../setup-neutron.yml

