---
- name: check system hostname
  command: hostname
  register: hostname
- name: set system hostname
  command: hostname {{inventory_hostname}}
  when: "hostname.stdout.find('localhost') != -1"
- yum: name={{item}} state=latest
  with_items:
    - git
    - strace
    - screen
    - vim-enhanced
    - libvirt-client
- name: create /var/lib/repos directory
  file: path=/var/lib/repos state=directory owner=root mode=0755

- git: repo=git://github.com/larsks/osctl
        dest=/var/lib/repos/osctl
  register: lastrun
- command: make -C /var/lib/repos/osctl install
  when: lastrun.changed
- git: repo=git://github.com/larsks/crux
        dest=/var/lib/repos/crux
  register: lastrun
- command: make -C /var/lib/repos/crux install
  when: lastrun.changed
- selinux: policy=targeted state={{selinux_state}}
- service: name=NetworkManager state=stopped
  ignore_errors: true
- yum: name=NetworkManager state=absent
- service: name=network state=running enabled=true
